sudo: required
language: java
jdk: oraclejdk11
services:
  - docker
#addons:
#  sonarcloud:
#    organization: he305
#    token:
#      secure: gUg0q5I7R6uQjsed2TuZTQHBdBn1MDbYShWUhG8kDUdnkMh7KN67ID/U2RUBkoXY7YkJ9UvWBnMaCIcRLub9jBuZ9qI2NcmuzfZ/lDu11Op8k3WBwmvcZQ9+GTHMoUOB10+PXWL4PrN5nqv2LHekG8uRFOiJYT07QiTXgyTPdi0WHJVR/aRElVi8SvSiUZjzmfqZeN0lsrwJHrR3dXF4MZMHs/VaPnAuXMMecdeKdEttNWRTVGzWtQ8kNQH8/nGebQcsGeka6CNLX8d1Lg0yEt91NAPnfssdMrCIAvqodXiNCss4ZuFr8sBRmMgJebp75BqeRnn1enaK3ph62CWDR4xlirsQC/5UqbWdCnENxMxfL21+GFgZATxTQ1qrqvnpdrE/mg7AoRD5ureO53GQps8aCnP2x5hOBNp+3yDVdHRpztxLrov45+/km+oAmIttrNCGln6q6ZrlrZsqyiayY91UKqvghohvp/Cf0hK2iRPcK+Xn2fC9zYF2tEnGYvVDT/3kORTBlbRb4ZoytBoaYF+i0H98qctgpyfqBD5Admo0Ars9p4pqSuwi5meNu6uXoxxhnbKBuK04NGQ9IsfMvFRuqDAF+PMrYuH+MAsW+LAvN7PiZ4y1iINQfAoO0Ny+hS4IdP0gViG5KtPVH3Tr61vwldbjRTYA1/o4TSNyKv0=
before_install:
  - chmod +x mvnw
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report
  - mvn sonar:sonar