spring:
  application:
    name: stream-feeder
  config:
    import: optional:file:.env[.properties]

producer-api:
  v1: http://127.0.0.1:8080
  v2:
    base_url: ${content-core-base-url:http://CORE/api}
    username: streamer-feeder
    password: streamer-feeder-password
    service-register-key: exampleserviceregisterkey

scheduler:
  delay: 60000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_HOST:http://localhost:9000/eureka}
  instance:
    instance-id: stream-feeder-instance-${random.uuid}

management:
  endpoint:
    health:
      show-components: always
      show-details: always
      status:
        http-mapping:
          up: 207
  endpoints:
    web:
      exposure:
        include: health, info, env, beans, metrics, prometheus
  info:
    env:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
info:
  app:
    name: Stream feeder