spring:
  config:
    import: optional:file:.env[.properties]

producer-api:
  v1: http://127.0.0.1:8080
  v2:
    base_url: ${content-core-base-url}
    username: streamer-feeder
    password: streamer-feeder-password
    service-register-key: exampleserviceregisterkey

scheduler:
  delay: 60000